apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-test
  namespace: default
  labels:
    team: digisos
spec:
  image: docker.adeo.no:5000/sosialhjelp-soknad-test:1.21
  port: 8080
  ingresses:
  - "https://sosialhjelp-test.nais.io/soknad"
  - "https://sosialhjelp-test.dev-sbs.nais.io/soknad"
  prometheus:
    enabled: true
    path: /prometheus
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: "1000m"
      memory: 512Mi
    requests:
      memory: 512Mi
  replicas:
    min: 1
    max: 2
  env:
  - name: MY_CUSTOM_VAR
    value: some_value