apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad
  namespace: {{namespace}}
  labels:
    team: digisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-soknad/sosialhjelp-soknad:{{version}}
  port: 8080
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  prometheus:
    enabled: true
    path: /prometheus
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      memory: 512Mi
  replicas:
    min: 2
    max: 2
  env:
    - name: APPRES_CMS_URL
      value: {{appresCmsUrl}}
