apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://sosialhhelp-soknad.prod-gcp.nais.io/sosialhjelp/soknad"
liveness:
  path: /sosialhjelp/soknad/internal/isAlive
  initialDelay: 5
  timeout: 1
  periodSeconds: 10
  failureThreshold: 10
readiness:
  path: /sosialhjelp/soknad/internal/isAlive
  initialDelay: 5
  timeout: 1
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 4m
    memory: 64Mi
replicas:
  min: 2
  max: 4
env:
  - name: DEKORATOR_MILJO
    value: prod
  - name: UNLEASH_API_URL
    value: https://unleash.nais.io/api/
  - name: REACT_APP_ENVIRONMENT
    value: prod-sbs
  - name: REACT_APP_API_BASE_URL
    value: https://www.nav.no/sosialhjelp/login-api/soknad-api/
  - name: REACT_APP_API_BASE_URL_WITH_ACCESS_TOKEN
    value: https://www.nav.no/sosialhjelp/login-api/soknad-api/
  - name: REACT_APP_INNSYN_URL
    value: https://www.nav.no/sosialhjelp/innsyn/
  - name: REACT_APP_MIN_SIDE_URL
    value: https://www.nav.no/minside/
  - name: REACT_APP_UTLOGGINGS_URL
    value: https://loginservice.nav.no/slo
