version: 2.1
orbs:
  sauce-connect: saucelabs/sauce-connect@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate version number and docker image tags
          command: |
            export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
            export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
            export VERSION=1.0_${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
            echo $VERSION > ./VERSION.txt

            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
      - run:
          name: Bygger Docker image
          command:
            docker build -t $DOCKER_TAG -f Dockerfile.circle .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DEPLOYMENT_PASSWORD" | docker login -u "$DEPLOYMENT_USERNAME" --password-stdin docker.pkg.github.com
            echo $DOCKER_TAG
            docker push $DOCKER_TAG
  testcafe:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

      working_directory: ~/repo

      steps:
        - checkout


        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: npm install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        # run tests!
        - run: npm testcafe

        - store_test_results:
            path: /tmp/test-results


workflows:
  version: 2.1
  build:
    jobs:
      - build
  testcafe:
    jobs:
      - testcafe
