version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate version number and docker image tags
          command: |
            export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
            export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
            export VERSION=1.0_${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
            echo $VERSION > ./VERSION.txt

            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
#      - run:
#          name: Bygger Docker image
#          command:
#            docker build -t $DOCKER_TAG -f Dockerfile.circle .
#      - run:
#          name: Pusher Docker image
#          command: |
#            echo "$DEPLOYMENT_PASSWORD" | docker login -u "$DEPLOYMENT_USERNAME" --password-stdin docker.pkg.github.com
#            echo $DOCKER_TAG
#            docker push $DOCKER_TAG

  release:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Release on Heroku
          command: |
            git remote add heroku https://eivindkn%40gmail.com:$HEROKU_AUTH_TOKEN@git.heroku.com/fleskesvor.git # FIXME: Replace with $CIRCLE_PROJECT_REPONAME
            git push heroku $CIRCLE_BRANCH:master --force

  browser-test:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Run browser tests
          command: |
            set -eo pipefail
            git clone https://github.com/navikt/sosialhjelp-tester.git
            cd sosialhjelp-tester
            git checkout feature/circleci-test

            npm install
            npm run saucelabs-soknad

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: feature/circleci-test
      - browser-test:
          requires:
            - release

