version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate version number and docker image tags
          command: |
            export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
            export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
            export VERSION=1.0_${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
            echo $VERSION > ./VERSION.txt

            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
      - run:
          name: Bygger Docker image
          command:
            docker build -t $DOCKER_TAG -f Dockerfile.circle .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DEPLOYMENT_PASSWORD" | docker login -u "$DEPLOYMENT_USERNAME" --password-stdin docker.pkg.github.com
            echo $DOCKER_TAG
            docker push $DOCKER_TAG
  testcafe:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Run testcafe tests
          command: npm run testcafe

workflows:
  version: 2.1
  build:
    jobs:
      - build
  testcafe:
    jobs:
      - testcafe
