version: 2.1

jobs:
  bygg:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Bygger Docker image
          command:
            docker build -t "navikt/sosialhjelp-soknad:${CIRCLE_SHA1}" -f Dockerfile.circle .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DEPLOYMENT_PASSWORD" | docker login -u "$DEPLOYMENT_USERNAME" --password-stdin docker.pkg.github.com
            docker push "navikt/sosialhjelp-soknad:${CIRCLE_SHA1}"

workflows:
  version: 2.1
  bygg-image:
    jobs:
      - bygg:
          context: NAIS deployment
