apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://sosialhjelp-soknad-dev.dev.nav.no/sosialhjelp/soknad"
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: dekoratoren.ekstern.dev.nav.no
        - host: digisos.dev.nav.no
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 50Mi
  replicas:
    min: 1
    max: 2
  env:
    - name: DEKORATOR_MILJO
      value: dev
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
    - name: REACT_APP_ENVIRONMENT
      value: dev-sbs
    - name: REACT_APP_API_BASE_URL
      value: https://www-q0.dev.nav.no/sosialhjelp/login-api/soknad-api/
    - name: REACT_APP_API_BASE_URL_WITH_ACCESS_TOKEN
      value: https://www-q0.dev.nav.no/sosialhjelp/login-api/soknad-api/
    - name: REACT_APP_INNSYN_URL
      value: https://www-q0.dev.nav.no/sosialhjelp/innsyn/
    - name: REACT_APP_MIN_SIDE_URL
      value: https://www.dev.nav.no/minside/
    - name: REACT_APP_UTLOGGINGS_URL
      value: https://loginservice.dev.nav.no/slo